name: Pearhill Painting
favicon: null
layout_spectrum: 0.74081
typography_spectrum: 0.5472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#92887e'
    - '#b8b679'
    - '#42462b'
    - '#281616'
    - '#d9d6c3'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.2070366321131587
purpose: []
